# Generated by Django 4.2.6 on 2024-01-06 22:09

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_alter_student_name_alter_student_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='memo',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='phone',
            field=models.CharField(blank=True, validators=[django.core.validators.RegexValidator(message='Phone number can only contain digits (0-9), plus sign (+), hyphen (-), and space ( ), but not in consecutive sequence.', regex='^[0-9+\\- ]+$')]),
        ),
    ]
