# Generated by Django 4.2.6 on 2024-01-12 23:33

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0004_alter_student_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='phone',
            field=models.CharField(blank=True, null=True, validators=[django.core.validators.RegexValidator(message='Phone number can only contain digits (0-9), plus sign (+), hyphen (-), and space ( ).', regex='^[0-9+\\- ]+$')]),
        ),
    ]
