# Generated by Django 4.2.6 on 2024-01-12 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='username',
            field=models.CharField(default='admin', max_length=255, unique=True, verbose_name='Username'),
            preserve_default=False,
        ),
    ]
