# Generated by Django 4.2.6 on 2023-12-24 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendarapp', '0003_alter_event_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='room',
            field=models.TextField(blank=True, choices=[('Room A', 'Room A'), ('Room B', 'Room B'), ('Room C', 'Room C')]),
        ),
    ]
