# Generated by Django 4.2.6 on 2023-12-24 20:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_alter_student_name_alter_student_phone'),
        ('calendarapp', '0005_remove_event_user_event_student'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='eventmember',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='event',
            name='student',
        ),
        migrations.AddField(
            model_name='eventmember',
            name='attendence',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='eventmember',
            name='student',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='event_members', to='students.student'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='eventmember',
            unique_together={('event', 'student')},
        ),
        migrations.RemoveField(
            model_name='eventmember',
            name='user',
        ),
    ]
