# Generated by Django 4.2.6 on 2023-12-24 21:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calendarapp', '0006_alter_eventmember_unique_together_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventmember',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='eventmember',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='eventmember',
            name='is_deleted',
        ),
        migrations.RemoveField(
            model_name='eventmember',
            name='updated_at',
        ),
    ]
