# Generated by Django 4.2.6 on 2023-12-30 21:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_alter_student_name_alter_student_phone'),
        ('calendarapp', '0008_alter_event_room'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='attendence',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='event',
            name='student',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='student_class', to='students.student'),
            preserve_default=False,
        ),
        migrations.AddConstraint(
            model_name='event',
            constraint=models.UniqueConstraint(fields=('student', 'start_time', 'end_time'), name='unique_student_timeslot'),
        ),
    ]
