# Generated by Django 4.2.6 on 2024-02-08 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendarapp', '0009_event_attendence_event_student_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='room',
            field=models.TextField(blank=True, choices=[('A', 'Room A'), ('B', 'Room B'), ('C', 'Room C'), ('OFF', 'OFF')]),
        ),
    ]
